#!/usr/bin/env python3
"""Render the workin On board feed from the shared attention board.

This tool no longer decides what is important. That decision lives in one
place - `tools/generate_attention.py`, which writes `current/attention.json` -
so the workin On tab and the web browser can never disagree about what needs
attention.

Responsibilities kept here:

- shape attention items into workin On board cards
- keep `masterindex.*` status keys stable so workin On upserts rather than duplicates
- emit `workinon://post` shortcut URLs
- write the human-readable folder README

Run `tools/generate_attention.py` first, or pass --refresh to do both.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlencode

LANE_ORDER = {"Needs Attention": 0, "Due Soon": 1, "Recent Activity": 2, "Summaries": 3}
PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def encode_workinon_url(key: str, text: str) -> str:
    return f"workinon://post?{urlencode({'key': key, 'text': text})}"


def board_card(item: dict) -> dict:
    """One attention item becomes one workin On card, carrying its action."""
    return {
        "id": item["id"],
        "type": item["kind"],
        "entityId": item.get("entityId"),
        "title": item["title"],
        "body": item["body"],
        "action": item["action"],
        "priority": item["priority"],
        "lane": item["lane"],
        "sortDate": item.get("sortDate"),
        "tags": item.get("tags", []),
        "deepLink": item["deepLink"],
        "statusKey": item["statusKey"],
    }


def digest_card(board: dict) -> dict:
    counts = board["counts"]
    watermark = board["watermark"]["lastReviewedAt"] or "never"
    return {
        "id": "masterindex-digest",
        "type": "summary",
        "entityId": None,
        "title": f"{counts['total']} items need attention",
        "body": f"{counts['high']} high, {counts['medium']} medium, {counts['low']} low. "
        f"{counts['suppressed']} conditions were suppressed as by-design or already resolved. "
        f"Last reviewed: {watermark}.",
        "action": "Open the MasterIndex browser for the full picture.",
        "priority": "high" if counts["high"] else "low",
        "lane": "Summaries",
        "sortDate": None,
        "tags": ["summary", "digest"],
        "deepLink": "site/index.html",
        "statusKey": "masterindex.summary.digest",
    }


def sort_cards(cards: list[dict]) -> list[dict]:
    return sorted(
        cards,
        key=lambda card: (
            LANE_ORDER.get(card["lane"], 4),
            PRIORITY_ORDER.get(card["priority"], 3),
            card["sortDate"] is None,
            str(card["sortDate"] or ""),
            card["title"],
        ),
    )


def shortcut_manifest_items(cards: list[dict]) -> list[dict]:
    manifest = []
    for card in cards:
        text = f"{card['title']} — {card['action']}" if card.get("action") else card["title"]
        manifest.append(
            {
                "id": card["id"],
                "title": card["title"],
                "statusKey": card["statusKey"],
                "url": encode_workinon_url(card["statusKey"], text),
                "entityId": card.get("entityId"),
                "type": card["type"],
                "priority": card["priority"],
            }
        )
    return manifest


def build_readme(feed: dict, board: dict) -> str:
    cards = feed["items"]
    by_lane = {lane: sum(1 for card in cards if card["lane"] == lane) for lane in LANE_ORDER}
    counts = board["counts"]
    return f"""# workin On Feed

Generated for MasterIndex on {feed["generatedAt"]}.

## Purpose

The operational board for `workin On`. It shows only what needs a decision or
an action; the web browser at `site/` remains the deep-dive surface.

## Where the content comes from

Every card is derived from `current/attention.json`, which is generated by
`tools/generate_attention.py` from the inventory, the task registry, and the
tuning rules in `current/attention-policy.json`. This tool does not decide what
matters on its own, so the workin On tab and the web page always agree.

## Files

- `board-feed.json` — generated board cards
- `shortcut-manifest.json` — ready-to-post `workinon://post` URLs for keyed status items

## Feed summary

- Total cards: {len(cards)}
- Needs Attention: {by_lane["Needs Attention"]}
- Due Soon: {by_lane["Due Soon"]}
- Recent Activity: {by_lane["Recent Activity"]}
- Summaries: {by_lane["Summaries"]}

By priority: {counts["high"]} high, {counts["medium"]} medium, {counts["low"]} low.
{counts["suppressed"]} conditions were suppressed as by-design or already resolved.

## Refreshing

```sh
python3 tools/generate_attention.py          # recompute what is actionable
python3 tools/generate_workinon_feed.py      # render the board
```

Or `python3 tools/generate_workinon_feed.py --refresh` to do both.

Once a review pass is done, `python3 tools/generate_attention.py --mark-reviewed`
stamps the watermark so already-seen changes stop reappearing.

## Notes

- Keys are namespaced as `masterindex.*` for safe upserts in workin On.
- Every card carries an `action` field describing what to actually do.
- Cards clear when the underlying condition is resolved in `current/index.json`.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("root", nargs="?", default=None, help="MasterIndex checkout root (defaults to this script's repository).")
    parser.add_argument("--refresh", action="store_true", help="Regenerate current/attention.json first.")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parents[1]
    attention_path = root / "current" / "attention.json"

    if args.refresh:
        subprocess.run([sys.executable, str(root / "tools" / "generate_attention.py"), str(root)], check=True)

    if not attention_path.exists():
        raise SystemExit(f"{attention_path} not found. Run tools/generate_attention.py first, or pass --refresh.")

    board = read_json(attention_path)
    cards = sort_cards([*(board_card(item) for item in board["items"]), digest_card(board)])

    feed = {
        "generatedAt": board["generatedAt"],
        "schemaVersion": "2.0",
        "sourceFiles": {"attention": "current/attention.json"},
        "intendedSurface": "workin On",
        "defaultLanes": ["Needs Attention", "Due Soon", "Recent Activity", "Summaries"],
        "watermark": board["watermark"],
        "itemCount": len(cards),
        "items": cards,
    }

    output_dir = root / "workinon"
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "board-feed.json").write_text(json.dumps(feed, indent=2, ensure_ascii=False) + "\n")
    (output_dir / "shortcut-manifest.json").write_text(
        json.dumps(
            {"generatedAt": feed["generatedAt"], "namespace": "masterindex", "items": shortcut_manifest_items(cards)},
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    (output_dir / "README.md").write_text(build_readme(feed, board))
    print(f"Generated {feed['itemCount']} workin On board cards in {output_dir}")


if __name__ == "__main__":
    main()
